import { readFileSync } from 'node:fs';
import { compare, releaseNotes } from '../tools/docs.mjs';
const version = JSON.parse(readFileSync(new URL('../package.json', import.meta.url))).version;
const en = readFileSync(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
const zh = readFileSync(new URL('../CHANGELOG.zh-TW.md', import.meta.url), 'utf8');
const problems = compare(en, zh, { changelog: true });
if (problems.length) throw new Error(`Bilingual changelog drift: ${problems.join('; ')}`);
const notes = releaseNotes(en, zh, version);
if (!notes) throw new Error(`Missing release notes for ${version}`);
process.stdout.write(notes);
